import React from 'react';

function Demo({ setActiveTab }) {
    const buttonStyle = {
        display: 'inline-block',
        outline: 0,
        border: 'none',
        cursor: 'pointer',
        fontWeight: 600,
        borderRadius: '4px',
        fontSize: '13px',
        height: '30px',
        backgroundColor: '#2542ac',
        color: 'white',
        padding: '0 20px',
        transition: 'background-color 0.3s',
    };

    const hoverStyle = {
        backgroundColor: '#1f3997',
    };

    const floatRight = {
        display: 'flex',
        justifyContent: 'flex-start',
        marginTop: '40px'
    };

    return (
        <div>
            <h1>Demo Simulator Directory</h1>

            <h2>Overview</h2>
            <p>The demo folder contains scripts to simulate the behavior of an RC car acting as a UDP client. Therefore, the content of this folder is not part of the actual backend and only serves testing purposes. This enables the possibility to test the entire data communication between backend, frontend, and a simulated car without any additional hardware.</p>
            <br/>

            <h2>Files</h2>
            <ul>
                <li><strong>UDPClient.py</strong></li>
                <li><strong>VehicleDataSimulator.py</strong></li>
            </ul>
            <br/>

            <h2>Running the Simulator</h2>
            <p>To start the simulated RC car, simply run the Python script within <code>UDPClient.py</code>. As this script uses the same configuration file as the entire backend, no further configurations are necessary.</p>
            <pre style={{marginLeft: '40px'}}>
                <code>python UDPClient.py</code>
            </pre>
            <p>If the <code>config.json</code> file has not been configured before, please follow these steps:</p>
            <ol>
                <li>Retrieve your current IP address using a Windows shell: <code>ipconfig</code></li>
                <li>Replace the IP address for both the server and client within <code>config.json</code></li>
                <li>If unsure, do not make any changes to the frontend, port, or buffer settings. Keep the default values.</li>
                <li>Run the simulator by executing the client script in <code>UDPClient.py</code></li>
            </ol>
            <br/>

            <h2>Purpose</h2>
            <p>The purpose of the demo directory is to provide a simulation that mimics the data typically generated by an RC car. This involves simulating speed and RPM as a dependent tuple of data and taking previously generated values into account to create the impression of acceleration or braking.</p>
            <p>Additionally, a UDP client is required to connect to the backend and send the generated data. Therefore, another purpose of this directory is to receive controls and settings from both the frontend and backend. These controls and settings are transferred as a binary stream and must be properly decoded. Using this client, the full decoding and extraction of required data is validated and tested.</p>
            <p>This data flow can be described as follows. The client sends the current speed, RPM, and battery percentage of the simulated car to the server (backend). Before being sent, this data is encoded into a predefined sequence of bytes to avoid unnecessary overhead. In return, the client receives the current controls (e.g., steering angle) and frontend settings (e.g., driving mode).</p>

            <div style={floatRight}>
                <button
                    style={buttonStyle}
                    onMouseEnter={e => e.target.style.backgroundColor = hoverStyle.backgroundColor}
                    onMouseLeave={e => e.target.style.backgroundColor = buttonStyle.backgroundColor}
                    onClick={() => setActiveTab('input')}
                >
                    previous
                </button>
            </div>
        </div>
    );
}

export default Demo;
