import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docsSidebar: [
    {
      type: "doc",
      id: "getting-started",
      label: "Getting Started"
    },
    {
      type: "doc",
      id: "hardware",
      label: "Hardware"
    },
    {
      type: "doc",
      id: "software",
      label: "Software"
    },
    {
      type: "doc",
      id: "frontend",
      label: "Frontend"
    },
    {
      type: "doc",
      id: "rc-car",
      label: "RC Car"
    },
  ],

};

export default sidebars;
